#!/usr/bin/env python3
"""Keep docs/feature-map.md aligned with the routes that exist.

Discovery is the Next.js `page.tsx` tree, FastAPI `@app.<method>` decorators,
and sidebar `href` literals. `docs/feature-map.json` must list exactly those
ids. Markdown is generated from the JSON. `--check` fails when they disagree.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APP_DIR = ROOT / "apps" / "web" / "src" / "app"
API_MAIN = ROOT / "apps" / "api" / "app" / "main.py"
SIDEBAR = ROOT / "apps" / "web" / "src" / "components" / "Sidebar.tsx"
MAP_JSON = ROOT / "docs" / "feature-map.json"
MAP_MD = ROOT / "docs" / "feature-map.md"

STATUSES = ("wired", "partial", "mocked", "missing")
ROUTE_FIELDS = ("id", "kind", "status", "does", "reach", "verify")
FLOW_FIELDS = ("id", "status", "does", "reach", "verify")
API_RE = re.compile(r'@app\.(get|post|put|delete|patch)\(\s*"([^"]+)"')
HREF_RE = re.compile(r'href:\s*"(/[^"]*)"')


def fail(message: str) -> None:
    print(f"FAIL feature-map: {message}")
    sys.exit(1)


def page_routes() -> list[str]:
    routes: list[str] = []
    for page in sorted(APP_DIR.rglob("page.tsx")):
        rel = page.parent.relative_to(APP_DIR)
        parts = [
            part
            for part in rel.parts
            if not (part.startswith("(") and part.endswith(")"))
            and not part.startswith("@")
        ]
        routes.append("/" + "/".join(parts) if parts else "/")
    return routes


def api_routes() -> list[str]:
    text = API_MAIN.read_text(encoding="utf-8")
    return [f"{method.upper()} {path}" for method, path in API_RE.findall(text)]


def sidebar_hrefs() -> list[str]:
    text = SIDEBAR.read_text(encoding="utf-8")
    return HREF_RE.findall(text)


def discover() -> tuple[list[str], set[str]]:
    pages = page_routes()
    apis = api_routes()
    links = sidebar_hrefs()
    if not pages:
        fail(f"no page.tsx files under {APP_DIR}")
    if not apis:
        fail(f"no FastAPI routes in {API_MAIN}")
    implemented = set(pages) | set(apis)
    required = list(pages)
    for api in apis:
        if api not in required:
            required.append(api)
    for href in links:
        if href not in implemented and href not in required:
            required.append(href)
    return required, implemented


def load_map() -> dict:
    if not MAP_JSON.is_file():
        fail(f"{MAP_JSON.relative_to(ROOT)} is missing")
    return json.loads(MAP_JSON.read_text(encoding="utf-8"))


def require_fields(entry: dict, fields: tuple[str, ...], label: str) -> None:
    for field in fields:
        value = entry.get(field)
        if not isinstance(value, str) or not value.strip():
            fail(f"{label} is missing {field}")


def render(data: dict) -> str:
    routes = data["routes"]
    flows = data["flows"]
    groups = (
        ("Pages", "page"),
        ("API", "api"),
        ("Linked paths with no page", "link"),
    )
    lines = [
        "# Feature map",
        "",
        "Generated from `docs/feature-map.json` by `python3 scripts/feature_map.py --write`.",
        "Do not edit this file by hand.",
        "",
        "`wired` means the flow persists or the endpoint does the real work.",
        "`partial` means some of that path is real and some is still a stub.",
        "`mocked` means the screen is static markup.",
        "`missing` means a nav target has no page.",
        "",
        "Verifying agents start here, then run the command named on the row.",
        "",
    ]
    for title, kind in groups:
        lines.append(f"## {title}")
        lines.append("")
        matched = [route for route in routes if route["kind"] == kind]
        if not matched:
            lines.append("None.")
            lines.append("")
            continue
        for route in matched:
            lines.append(f"### `{route['id']}`")
            lines.append("")
            lines.append(f"Status: {route['status']}.")
            lines.append("")
            lines.append(route["does"])
            lines.append("")
            lines.append(f"Reach it from {route['reach']}.")
            lines.append("")
            lines.append(f"Verify: {route['verify']}")
            lines.append("")
    lines.append("## Flows that are not routes")
    lines.append("")
    if not flows:
        lines.append("None.")
        lines.append("")
    for flow in flows:
        lines.append(f"### {flow['id']}")
        lines.append("")
        lines.append(f"Status: {flow['status']}.")
        lines.append("")
        lines.append(flow["does"])
        lines.append("")
        lines.append(f"Reach it from {flow['reach']}.")
        lines.append("")
        lines.append(f"Verify: {flow['verify']}")
        lines.append("")
    return "\n".join(lines)


def check(data: dict, required: list[str], implemented: set[str]) -> None:
    routes = data.get("routes")
    flows = data.get("flows")
    if not isinstance(routes, list) or not isinstance(flows, list):
        fail("feature-map.json needs routes and flows arrays")

    ids: list[str] = []
    pages = set(page_routes())
    apis = set(api_routes())
    for route in routes:
        if not isinstance(route, dict):
            fail("a route entry is not an object")
        require_fields(route, ROUTE_FIELDS, "a route")
        route_id = route["id"]
        if route["status"] not in STATUSES:
            fail(f"{route_id} has status {route['status']}")
        if route_id in pages and route["kind"] != "page":
            fail(f"{route_id} is a page but kind is {route['kind']}")
        elif route_id in apis and route["kind"] != "api":
            fail(f"{route_id} is an API route but kind is {route['kind']}")
        elif route_id not in implemented and route["kind"] != "link":
            fail(f"{route_id} has no page or endpoint but kind is {route['kind']}")
        if route_id in implemented and route["status"] == "missing":
            fail(f"{route_id} exists but is marked missing")
        if route_id not in implemented and route["status"] != "missing":
            fail(f"{route_id} has no page or endpoint, so status must be missing")
        ids.append(route_id)

    if len(ids) != len(set(ids)):
        fail("duplicate route ids in feature-map.json")

    missing = [route_id for route_id in required if route_id not in set(ids)]
    extra = [route_id for route_id in ids if route_id not in set(required)]
    if missing or extra:
        detail = []
        if missing:
            detail.append("add " + ", ".join(missing))
        if extra:
            detail.append("remove " + ", ".join(extra))
        fail("route set changed. " + ". ".join(detail))

    for flow in flows:
        if not isinstance(flow, dict):
            fail("a flow entry is not an object")
        require_fields(flow, FLOW_FIELDS, "a flow")
        if flow["status"] not in STATUSES:
            fail(f"flow {flow['id']} has status {flow['status']}")

    expected = render(data)
    actual = MAP_MD.read_text(encoding="utf-8") if MAP_MD.is_file() else ""
    if actual != expected:
        fail(
            "docs/feature-map.md is stale. Run python3 scripts/feature_map.py --write"
        )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    if args.check == args.write:
        fail("pass exactly one of --check or --write")

    required, implemented = discover()
    data = load_map()
    if args.write:
        if not isinstance(data.get("routes"), list):
            fail("feature-map.json needs a routes array")
        MAP_MD.write_text(render(data), encoding="utf-8")
        print(f"wrote {MAP_MD.relative_to(ROOT)}")

    check(data, required, implemented)
    print(f"PASS feature-map: {len(required)} routes")


if __name__ == "__main__":
    main()
